### ISSUE TITLE
Brain Dump

### ISSUE THREAD

**Issue by chaupow** [chaupow/VL.Devices.Kinect#1]
# Kinect in Beta

#### Things I know

- [nodes/plugins/Devices/MSKinect/Nodes](https://github.com/vvvv/vvvv-sdk/tree/develop/vvvv45/addonpack/src/nodes/plugins/Devices/MSKinect/Nodes) is the code that implements the Nodes that can be used in beta and are annotated with a `p`:
- ![2019-12-18 (1)](https://user-images.githubusercontent.com/804027/71090268-eb0ae600-21a2-11ea-931a-637abe6486b7.png)
- They implement interfaces such as `IPluginDXTexture2` to make them usable in vvvv
- The code for the `m` nodes are [here](https://github.com/vvvv/vvvv-sdk/tree/392235e61626016707481b674499fd76efb0a123/vvvv45/addonpack/lib/nodes/modules/Kinect)

#### Questions

- Wth is [this](https://github.com/vvvv/vvvv-sdk/tree/392235e61626016707481b674499fd76efb0a123/vvvv45/addonpack/src/nodes/plugins/Devices/MSKinect/Nodes#L8) and where does it point to
- What's the difference between `p` and `m` nodes?

# Kinect2 in Gamma

#### Things I know

- The implementation of the nodes is completely in [here](https://github.com/vvvv/VL.Devices.Kinect2/blob/master/VL.Devices.Kinect2.vl) and unless I wanna write xml by hand, it's best to program them visually: 
![2019-12-18 (2)](https://user-images.githubusercontent.com/804027/71091733-f9a6cc80-21a5-11ea-9bd8-5029215be11f.png)
- https://github.com/vvvv/VL.Devices.Kinect2/tree/master/src is helper code that can be used when visually programming the nodes, example: ![2019-12-18 (4)](https://user-images.githubusercontent.com/804027/71092419-79816680-21a7-11ea-845d-c5f3c7061ad3.png)

#### Questions

- What is [VL.Devices.Kinect2.HDE.vl](https://github.com/vvvv/VL.Devices.Kinect2/blob/master/VL.Devices.Kinect2.HDE.vl)?
- Is parts of https://github.com/vvvv/VL.Devices.Kinect2/tree/master/src getting autogenerated? 

# THE PLAN

#### ~~Naive approach #1~~

- ~~clone https://github.com/vvvv/VL.Devices.Kinect2~~
- ~~replace `Kinect2` with `Kinect`~~
- ~~swap the reference to the V2 SDK lib to the KinectV1 dll~~
- ~~adjust the resolution/pixel calculations to the Kinect V1 resolution~~
- ~~resolve all build errors~~

Not sure this is the way to go. too weird. too seemingly complicated.

#### Attempt 2

- [x] start from within vvvv, open a project, link it to the Kinect V1 dlls
- [x] **visually** re-program the nodes that are in beta:
  - [x] Kinect
  - [x] RGB 
  - [ ] Face
  - [ ] Depth
  - [ ] World
  - [ ] Player
  - [ ] RGBDepth
  - [ ] Skeleton
  - [ ] SmoothSettings
- [ ] only if you hit a wall, write c# code in textual programming to write helper functions
- [ ] figure out how to proceed

**Comment by azeno** [comment]
What is VL.Devices.Kinect2.HDE.vl?
HDE = HybridDevelopmentEnvironment - well not a fan either but that's what we came up with a decade ago ;) In any case, it means this patch gets loaded by the patch editor. It can contain extensions which get picked up by the editor UI. For now this only means to patch your own tooltips, but it will probably also be possible to patch your own IO boxes in the future. In any case, the Kinect2 library uses it to render the Skeleton in the tooltip which is very handy.

**Comment by chaupow** [comment]
stale. things have moved a lot
